sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yadgiriv/docker-react-new -f Dockerfile.dev .

script:
  - docker run -e CI=true yadgiriv/docker-react-new npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-223892559068'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
